os:
  - linux
  - osx
  - windows
arch:
  - i386
  - amd64

julia:
  - 1.3
  - nightly

branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
    - julia: nightly
  fast_finish: true

language: julia

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
