os:
  - linux
  - osx
arch:
  - x64
  - x86

branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - os: windows
      arch: x64
      julia: 1.3
    - os: windows
      arch: x86
      julia: 1.3
      name: "Julia 1 (32bit)"
    - os: windows
      arch: x64
      julia: nightly
julia:
  - "1.3"
  - nightly

language: julia

os:
  - linux
  - osx
  - windows

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
